dep-id:
  #"6BS4TPNWMAHT2RPM": "DS4_Fleet_Supervision"  
  #"SD7XLSX22QF3C44D": "DS4_Alarm"
  #"CXH6ZUBKHQXMNGTO": "HLS_PRS"
  #"GP5RSA7JSWFGJNF5": "DS4_Dashboard"
  #"JYCTJZYFGXLHFRTE": "HVAC_Monitoring"
  #"VKWEIYRHPVCUHVRQ": "DS4_VoyageSummary"
  #"EMOQE6XVSCENIPJO": "DS4_RoutePlanning"
  #"TLSZGNGAYUVT2TIY": "DS4_RouteManager"
  #"LD5Q7PNSQZUMPNJF": "DS4_MotionMonitoring"
  #"6OJPUDMLCI4G4I26": "DS4_FatigueLife"
  #"5IDRHGCHXA37GZGK": "DS4_Cont_Loss"
  #"DGX5X43EBB2ID5MQ": "DS4_BOG_Prediction"
  #"2EYAL7HHTYDUUJMW": "DS4_Emission"
  #"PIWFTFMNBJEEAWSO": "DS4_SGM"
  #"GQOVW2CYM2NC5QV7": "DS4_LFSS"
  #"TRNKOHC7NM5PL42M": "DS4_ALS"
  #"WJLPDSOTY6UTFBOO": "DS4_Sloshing_monitoring"
  #"RIZTEF7ZHZVIZOXX": "anvil_extras"
  #"NC33Q2DAKDG5XSJI": "DS4_FRS"
  #"XZDE5AP7E4YVMXIO": "DS4_LPGRS"
  #"4WRFYGONQ3YGVTLN": "DS4_NRS"
  #"Z6O35DHDENDAEKHY": "DS4_VLCC_FGSS"
  #"XX5WI6DIXK6ZHVHG": "DS4_VLCC_ME"
  "XOG2Z33QD7NF2ORR": "DS4_FSRU_Regas"
  "VGZPJ7KCUA2XSNX5": "DataManager"
  #"WPDYBQQV27BP76ZP": "VoyageSummary"
