dep-id:
  "BNJG4NHUDHE34RYJ": "DataManager"
  "K2PG4BQMEJ5P52ZX": "DS4_FRS"
  "CEMPQW5QDMVLKF2Q": "DS4_Fleet_Supervision"  
  "APPGYVCDTVO5GH5U": "DS4_Alarm"
  "VHYXTWLQ5FESNFYY": "HLS_PRS"
  "I5GCHDJAHMZYUK35": "DS4_Dashboard"
  "IBIBBDZXOPYA56HT": "HVAC_Monitoring"
  "J6YIVZQJGFZRSQTQ": "DS4_VoyageSummary"
  "2UFRR662VQ67AKY4": "DS4_RoutePlanning"
  "SYLSNGMQ76GXEWKU": "DS4_RouteManager"
  "FE4ZT4VPGILMUNCX": "DS4_MotionMonitoring"
  "LRLP55DYKWYBLXP5": "DS4_FatigueLife"
  "7Q6LJHSUHQB3O32W": "DS4_Cont_Loss"
  "QOLI4R3WONFTES3C": "DS4_BOG_Prediction"
  "7UD5QQ6WASWUCSUB": "DS4_Emission"
  "CETQNGWGJA73PWJS": "DS4_SGM"
  "6M45ASOQURQRN447": "DS4_LFSS"
  "RHYW5QSM3GSPUHDH": "DS4_ALS"
  "CTOADZO77MEIJ6HN": "DS4_Sloshing_monitoring"
  "GCAJHKHW7CZ2AJJG": "anvil_extras"
  "MCO5JIRDGVWB4ZTJ": "DS4_LPGRS"
  "X72OVB6X7ATMNWXA": "DS4_NRS"
  "DFB5J7ATMXWBEOMY": "DS4_VLCC_FGSS"
  "CXKJEAXOOLKLR6GZ": "DS4_VLCC_ME"
  "L7CDZEELH5KSQPD6": "DS4_FSRU_Regas"
  "V55GNT3NOS4QIVZ5": "VoyageSummary"
  "HCAYMIDS5FJUGVGD": "DS4_FSRU_GE"
